#ifndef SKENGIO_DEFINES

#define SKENGIO_DEFINES

#define PROJ_MATRIX_UNIFORM_NAME "projMatrix"
#define VIEW_MATRIX_UNIFORM_NAME "viewMatrix"
#define MODEL_MATRIX_UNIFORM_NAME "modelMatrix"

#define SCENE_DEFAULT_START 0.0f
#define SCENE_DEFAULT_END 60.0f

#endif